plugins {
    id "org.springframework.boot" version "3.5.14" apply false
    id "io.spring.dependency-management" version "1.1.7" apply false
}

ext {
    embeddedRedisVersion = "0.7.2"
    springBootRedissonVersion = "3.52.0"
    springCloudVersion = "2025.0.2"
    springDocOpenAPIUIVersion = "2.8.15"
}

subprojects {

    def hasSrcFolder = new File("${projectDir}/src").exists()
    if (hasSrcFolder) {

        apply plugin: "java-library"
        apply plugin: "org.springframework.boot"
        apply plugin: "io.spring.dependency-management"

        group = "com.jong"
        version = "0.0.1-SNAPSHOT"
        description = "msa-board"

        java {
            toolchain {
                languageVersion = JavaLanguageVersion.of(21)
            }
        }

        repositories {
            mavenCentral()
        }

        dependencyManagement {
            imports {
                mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
            }
            dependencies {
                dependency "it.ozimov:embedded-redis:${embeddedRedisVersion}"
                dependency "org.redisson:redisson-spring-boot-starter:${springBootRedissonVersion}"
                dependency "org.springdoc:springdoc-openapi-starter-webmvc-ui:${springDocOpenAPIUIVersion}"
                dependency "org.springdoc:springdoc-openapi-starter-webflux-ui:${springDocOpenAPIUIVersion}"
            }
        }

        dependencies {
            compileOnly "org.projectlombok:lombok"
            annotationProcessor "org.projectlombok:lombok"
            testCompileOnly "org.projectlombok:lombok"
            testAnnotationProcessor "org.projectlombok:lombok"
        }
    }
}
