plugins {
    id "org.springframework.boot" version "3.5.14" apply false
    id "io.spring.dependency-management" version "1.1.7" apply false
}

ext {
    embeddedRedisVersion = "0.7.2"
}

subprojects {

    def hasSrcFolder = new File("${projectDir}/src").exists()
    if (hasSrcFolder) {

        apply plugin: "java-library"
        apply plugin: "org.springframework.boot"
        apply plugin: "io.spring.dependency-management"

        group = "com.jong"
        version = "0.0.1-SNAPSHOT"
        description = "msa-board"

        java {
            toolchain {
                languageVersion = JavaLanguageVersion.of(21)
            }
        }

        repositories {
            mavenCentral()
        }

        dependencyManagement {
            dependencies {
                dependency "it.ozimov:embedded-redis:${embeddedRedisVersion}"
            }
        }

        dependencies {
            compileOnly "org.projectlombok:lombok"
            annotationProcessor "org.projectlombok:lombok"
            testCompileOnly "org.projectlombok:lombok"
            testAnnotationProcessor "org.projectlombok:lombok"
        }
    }
}
