spring:
  application:
    name: micro-member
  config:
    import: optional:configserver:http://localhost:18888
  cloud:
    config:
      label: local
  profiles:
    active:
    - micro-common
    - micro-member

logging:
  config: classpath:logback-${spring.application.name}.xml