server:
  port: 8001

spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mariadb://localhost:13306/msa_board
      username: root
      password: root

springdoc:
  title: Member Micro Service RESTful API
  version: 1.0.0