dependencies {
    implementation project(":msa-board-common")
    implementation "org.springframework.boot:spring-boot-starter-json"
    testImplementation "org.springframework.boot:spring-boot-starter-test"
}

bootJar {
    enabled = false
}

jar {
    enabled = false
}

test {
    useJUnitPlatform()
}

