configurations {
    testImplementation {
        extendsFrom compileOnly
    }
}

dependencies {

    // Internal
    implementation project(":msa-board-common")

    // AOP & Json
    implementation "org.springframework.boot:spring-boot-starter-aop"
    implementation "org.springframework.boot:spring-boot-starter-json"
    implementation 'org.springframework.cloud:spring-cloud-starter-openfeign'

    // Redis & Redis Reactive & Redisson
    compileOnly "org.springframework.boot:spring-boot-starter-data-redis"
    compileOnly "org.springframework.boot:spring-boot-starter-data-redis-reactive"
    compileOnly "org.redisson:redisson-spring-boot-starter"

    // JPA & Query DSL
    compileOnly "org.springframework.boot:spring-boot-starter-data-jpa"
    compileOnly "com.querydsl:querydsl-jpa::jakarta"

    // Kafka
    compileOnly "org.springframework.kafka:spring-kafka"

    // Elasticsearch
    compileOnly "org.springframework.boot:spring-boot-starter-data-elasticsearch"

    // Open Feign
    compileOnly "org.springframework.cloud:spring-cloud-starter-openfeign"

    // Test
    testImplementation project(":msa-board-support-test")
    testImplementation "org.springframework.boot:spring-boot-starter-test"
    testImplementation "org.springframework.boot:spring-boot-testcontainers"
    testImplementation "org.springframework.kafka:spring-kafka-test"
    testImplementation "org.testcontainers:junit-jupiter"
    testImplementation "org.testcontainers:elasticsearch"
    testImplementation "it.ozimov:embedded-redis"
    testRuntimeOnly "com.h2database:h2"
}

bootJar {
    enabled = false
}

jar {
    enabled = true
}

test {
    useJUnitPlatform()
}
