version: "3.8"

services:

  msa-board-elasticsearch-cluster-node-1:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
    container_name: msa-board-elasticsearch-cluster-node-1
    hostname: msa-board-elasticsearch-cluster-node-1
    environment:
      - TZ=Asia/Seoul
      - LC_ALL=C.UTF-8
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - node.name=msa-board-elasticsearch-cluster-node-1
      - cluster.name=msa-board-elastic-cluster
      - discovery.seed_hosts=msa-board-elasticsearch-cluster-node-1,msa-board-elasticsearch-cluster-node-2,msa-board-elasticsearch-cluster-node-3
      - cluster.initial_master_nodes=msa-board-elasticsearch-cluster-node-1,msa-board-elasticsearch-cluster-node-2,msa-board-elasticsearch-cluster-node-3
      - node.roles=master,data
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./plugins:/usr/share/elasticsearch/plugins
      - ./data/cluster-node-1:/usr/share/elasticsearch/data

  msa-board-elasticsearch-cluster-node-2:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
    container_name: msa-board-elasticsearch-cluster-node-2
    hostname: msa-board-elasticsearch-cluster-node-2
    environment:
      - TZ=Asia/Seoul
      - LC_ALL=C.UTF-8
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - node.name=msa-board-elasticsearch-cluster-node-2
      - cluster.name=msa-board-elastic-cluster
      - discovery.seed_hosts=msa-board-elasticsearch-cluster-node-1,msa-board-elasticsearch-cluster-node-2,msa-board-elasticsearch-cluster-node-3
      - cluster.initial_master_nodes=msa-board-elasticsearch-cluster-node-1,msa-board-elasticsearch-cluster-node-2,msa-board-elasticsearch-cluster-node-3
      - node.roles=master,data
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./plugins:/usr/share/elasticsearch/plugins
      - ./data/cluster-node-2:/usr/share/elasticsearch/data

  msa-board-elasticsearch-cluster-node-3:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
    container_name: msa-board-elasticsearch-cluster-node-3
    hostname: msa-board-elasticsearch-cluster-node-3
    environment:
      - TZ=Asia/Seoul
      - LC_ALL=C.UTF-8
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - node.name=msa-board-elasticsearch-cluster-node-3
      - cluster.name=msa-board-elastic-cluster
      - discovery.seed_hosts=msa-board-elasticsearch-cluster-node-1,msa-board-elasticsearch-cluster-node-2,msa-board-elasticsearch-cluster-node-3
      - cluster.initial_master_nodes=msa-board-elasticsearch-cluster-node-1,msa-board-elasticsearch-cluster-node-2,msa-board-elasticsearch-cluster-node-3
      - node.roles=master,data
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./plugins:/usr/share/elasticsearch/plugins
      - ./data/node-3:/usr/share/elasticsearch/data

  msa-board-elasticsearch-cluster-coordinator:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
    container_name: elasticsearch-coordinator
    hostname: elasticsearch-coordinator
    environment:
      - TZ=Asia/Seoul
      - LC_ALL=C.UTF-8
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - node.name=elasticsearch-coordinator
      - cluster.name=msa-board-elastic-cluster
      - discovery.seed_hosts=msa-board-elasticsearch-cluster-node-1,msa-board-elasticsearch-cluster-node-2,msa-board-elasticsearch-cluster-node-3
      - cluster.initial_master_nodes=msa-board-elasticsearch-cluster-node-1,msa-board-elasticsearch-cluster-node-2,msa-board-elasticsearch-cluster-node-3
      - node.roles=[]
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 19200:9200
    volumes:
      - ./plugins:/usr/share/elasticsearch/plugins
